/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


public class General_Window extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public General_Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_AutomataPila = new javax.swing.JButton();
        btn_ReconocedorDescendente = new javax.swing.JButton();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Teoria De Compiladores.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 730, 150));

        btn_AutomataPila.setText("Automta De Pila");
        btn_AutomataPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AutomataPilaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_AutomataPila, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 180, 90));

        btn_ReconocedorDescendente.setText("Reconocedor Descendente");
        btn_ReconocedorDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReconocedorDescendenteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ReconocedorDescendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 180, 90));

        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Blue.png"))); // NOI18N
        getContentPane().add(lbl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 912, 642));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AutomataPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AutomataPilaActionPerformed
     Automata_De_Pila_Window  Ap = new Automata_De_Pila_Window(); // Declarar Ventana General
     Ap.setLocationRelativeTo(null); // Centrar ventana general
     Ap.setVisible(true);  // Mostrar Ventana General
    }//GEN-LAST:event_btn_AutomataPilaActionPerformed

    private void btn_ReconocedorDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReconocedorDescendenteActionPerformed
     Reconocedor_Descendente Rd = new Reconocedor_Descendente(); // Declarar Ventana General
     Rd.setLocationRelativeTo(null); // Centrar ventana general
     Rd.setVisible(true);  // Mostrar Ventana General
    }//GEN-LAST:event_btn_ReconocedorDescendenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AutomataPila;
    private javax.swing.JButton btn_ReconocedorDescendente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Fondo;
    // End of variables declaration//GEN-END:variables
}
