/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


public class Reconocedor_Descendente extends javax.swing.JFrame {

    public Reconocedor_Descendente() {
        initComponents();
        bloquear();
        String a = "1. A = aC\n"
                +  "2. A = bBc\n"
                +  "3. B = aA\n"
                +  "4. B = bB\n"
                +  "5. C = aCa\n"
                +  "6. C = bBcc\n"
                +  "7. C = |\n";
        txtGeneral.setText(a);
    }
    
    public void bloquear() {
        //btnVerMatriz.setEnabled(false);
        //btnGenerarHilera.setEnabled(false);
    }

    public void desbloquear() {
        //btnVerMatriz.setEnabled(true);
        //btnGenerarHilera.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Name = new javax.swing.JLabel();
        txtGeneral = new java.awt.TextArea();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Reconocedor Descendente.png"))); // NOI18N
        getContentPane().add(lbl_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 780, 150));
        getContentPane().add(txtGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 440, 270));

        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Blue.png"))); // NOI18N
        getContentPane().add(lbl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JLabel lbl_Name;
    private java.awt.TextArea txtGeneral;
    // End of variables declaration//GEN-END:variables
}
