/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ArchivoC;
import Control.Utilidades;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maraton
 */
public class Ver_Matriz_Window extends javax.swing.JFrame {

    private ArchivoC archivo;
    private DefaultTableModel modelo;
    private JFrame t;
    private BufferedImage imagen; // Creacion de la imagen

    public Ver_Matriz_Window(ArchivoC c, JFrame t) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.archivo = c;
        this.t = t;
        generar();
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }
        });

    }
    private void close(){
        t.setVisible(true);

        
    } 

    void generar() {
        Utilidades u = new Utilidades();
        u.generarCombobox(jComboBox1, archivo);

    }

    public void crearTabla(String simbolos) {
        modelo = new DefaultTableModel();
        for (int i = 0; i < simbolos.length(); i++) {
            modelo.addColumn(simbolos.charAt(i));
        }
        this.table1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        scrollpanel1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        btnFoto = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 190, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollpanel1.setViewportView(table1);

        getContentPane().add(scrollpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 320));

        btnFoto.setText("Foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 80, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Blue.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        crearTabla(archivo.getExpresion().getSimboloEntrada());
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String seleccionado = jComboBox1.getSelectedItem().toString();
            Utilidades u = new Utilidades();
            u.generarTabla(modelo, archivo, seleccionado);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        imagen = screenImagen(scrollpanel1);
        // seleccionar la carpeta donde guardaremos la imagen
        JFileChooser jfc = new JFileChooser();
        jfc.setCurrentDirectory(new File("c:\\"));
        jfc.setFileFilter(new FileNameExtensionFilter("Imagen Png", "png"));
        int retorno = jfc.showSaveDialog(this);
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        if (retorno == JFileChooser.APPROVE_OPTION) {
            try {
                File sfile = new File(jfc.getSelectedFile() + ".png");
                ImageIO.write(imagen, "png", sfile);
                JOptionPane.showMessageDialog(this, "Screenshot generado con exito");
            } catch (IOException ioe) {
                System.out.println("write: " + ioe.getMessage());
            }
        }
    }//GEN-LAST:event_btnFotoActionPerformed

    // Funcion para tomar pantallazo de un componente
    public static BufferedImage screenImagen(Component componente) {

        BufferedImage image = new BufferedImage(componente.getWidth(),
                componente.getHeight(), BufferedImage.TYPE_INT_RGB);
        // call the Component's paint method, using
        // the Graphics object of the image.
        componente.paint(image.getGraphics()); // alternately use .printAll(..)
        return image;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFoto;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JScrollPane scrollpanel1;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
